spring.application.name=inventario-service
server.port=8082
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/inventario}
spring.datasource.username=${DB_USER:inventario}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.connection-timeout=5000
spring.flyway.schemas=inventario
spring.flyway.default-schema=inventario
app.auth-url=${AUTH_URL:http://localhost:8091}
server.error.include-message=never
management.endpoints.web.exposure.include=health
