spring.application.name=usuarios-service
server.port=8081
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/inventario}
spring.datasource.username=${DB_USER:inventario}
spring.datasource.password=${DB_PASSWORD}
spring.flyway.schemas=usuarios
spring.flyway.default-schema=usuarios
spring.datasource.hikari.connection-timeout=5000
server.error.include-message=never
app.master.identification=${MASTER_IDENTIFICATION:}
app.master.name=${MASTER_NAME:Administrador principal}
app.master.password=${MASTER_PASSWORD:}
